### ISSUE TITLE
[to be discussed] updating templates that have been identified changes in chevron

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tlg-catalog#15]

**Comment by Melkiades** [comment]
I think it is a valid point. Why discussion?

**Comment by edelarua** [comment]
I've started compiling a list of changes that have been made in chevron for this issue but still have a few more templates to go through.

**Comment by edelarua** [comment]
Differences in `chevron` templates as compared to TLG Catalog:

## All templates
- Fixed single decimal place
- All default to arm var "ACTARM"
- All `map`s hard-coded (not dependent on whether levels are present in data)

## AET01
- AEs are different
- extra filters: ANL01FL == "Y"
- summarize_num_patients instead of first 2 count_* funs (adae lyt)
- uses count_patients_with_event instead of count_values (adsl lyt)

## AET01_AESI
- filters on "ANL01FL" = "Y" instead of STUDYID in lyt
- ATOXGR instead of AETOXGR
- indent optional lines ("No. of ...") where applicable

## AET02
- labels MedDRA System Organ Class and MedDRA Preferred Term
- extra filters: ANL01FL == "Y"
- uses summarize_num_patients instead of analyze_num_patients

## AET03
- extra filters: ANL01FL == "Y"
- chevron missing third topleft label

## AET04
- labels MedDRA System Organ Class and MedDRA Preferred Term
- filters: ANL01FL == "Y", ATOXGR not missing
- entire table redesigned (see chevron lyt)

## CMT01A
- labels ATC Class Level 2 and Other Treatment
- only filters ANL01FL == "Y"

## CMT02_PT
- label Other Treatment
- only filters ANL01FL == "Y"
- uses summarize_num_patients instead of analyze_num_patients
- splits rows by DOMAIN (new var = "CM" for all rows)
- indents CMDECOD terms

## DMT01
- row vars: Age, Age group, Sex, Ethnicity, Race
- creates DOMAIN var = "ADSL" for all rows
- row split on DOMAIN before summarize_vars

## DST01
- "Ongoing" between completed and discont. study rows
- created as 2 separate tables in chevron?

## DTHT01
- also created as 2 separate tables in chevron?

## EGT01
- initial row split by PARAM
- colsplit labels Value at Visit and Change from Baseline
- filters: ANL01FL == "Y"

## EGT02
- labels Assessment and Abnormality
- `variables` specified in count_abnormal: id = "USUBJID", basline = "BNRIND"
- capitalized "Low" and "High"
- filters out missing ANRIND

## EGT03
- no differences

## EGT05_QTCAT
- don't hardcode msec unit in AVALCAT1 and CHGCAT1 derivation
- AVALCAT1 / CHGCAT1 thresholds should be taken from dataset (not hardcoded)
- initial row split by PARAM (drop_split_levels)
- filters out zero rows by default
- check for warnings
- hide Chg. from Baseline in BASELINE split

## EXT01
- PARAMCD levels reordered: `c("TNDOSE", "DOSE", "NDOSE", "TDOSE")`

## LBT01
- initial row split by PARAM (drop_split_levels)
- filters: ANL01FL == "Y"
- colsplit labels Value at Visit and Change from Baseline
- set BASELINE CHG values to NULL (no output)
- some stats have additional digits in output

## LBT04
- extra filters: PARCAT2 == "SI", ANRIND not missing
- labels Laboratory Test and Direction of Abnormality
- no split fun for PARCAT1
- drop_split_levels split fun for PARAM
- count_abnormal `abnormal = list(Low = c("LOW", "LOW LOW"), High = c("HIGH", "HIGH HIGH"))`

## LBT05
- simpler pruning function

## LBT07
- fixed topleft label indentation
- AVISIT filter not needed if ONTRTFL derivation is fixed in scda
- no droplevels in filtering
- uses ATOXGR not AETOXGR
- derivation of GRADE_DIR - LOW must have WGRLOFL == "Y", HIGH must have WGRHIFL == "Y"

## LBT14
- first split on PARAM not PARAMCD with drop_split_levels
- more indentation of row splits
- fixed topleft label indentation
- no (n) in row split level labels
- only filter: WGRLOFL == "Y"
- no h_adsl_adlb_merge_using_worst_flag step
- count_occurrences drop = FALSE

## MHT01
- labels MedDRA System Organ Class and MedDRA Preferred Term
- indented after each SOC
- filters: ANL01FL == "Y"

## PDT01
- labels Category and Description
- indented after each DECOD term
- summarize_num_patients instead of analyze_num_patients

## PDT02
- labels Primary Reason and Description
- summarize_num_patients instead of first analyze_num_patients
- second summarize_num_patients uses unique_count
- id explicitly set to USUBJID for count_occurrences

## VST01
- initial row split by PARAM with drop_split_levels
- no definition of range label
- only filters: ANL01FL == "Y"
- needs to be fixed like LBT01 to not show BASELINE CHG output

## VST02
- labels Assessment and Abnormality
- extra filters: ANRIND not missing
- converts LOW LOW and HIGH HIGH to LOW and HIGH in preprocessing instead of including both in `abnormal` arg (don't change in tlg-c)
- capitalize "low" and "high" in `abnormal` arg.

**Comment by edelarua** [comment]
Additionally, in `scda`, the derivation of ONTRTFL should be updated: ONTRTFL = "Y" for non-SCREENING/BASELINE visits.

**Comment by shajoezhu** [comment]
Thanks so much Emily!

**Comment by edelarua** [comment]
Closed by https://github.com/insightsengineering/tlg-catalog/issues/58 https://github.com/insightsengineering/tlg-catalog/issues/59 https://github.com/insightsengineering/tlg-catalog/issues/61
