### ISSUE TITLE
removed/replace the deprecated function and argument

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/tlg-catalog#161]
### What happened?

Many examples and code chunks display deprecation warnings from 'tern' or other packages(need investigation). These warnings suggest replacing outdated functions or arguments with newer, stable alternatives.
e.g
<img width="610" alt="image" src="https://github.com/insightsengineering/tlg-catalog/assets/6700955/432f18c0-0856-4c29-97ce-347e7061df67">

**Comment by edelarua** [comment]
Hi @kartikeyakirar,

These warnings are only visible in the development version. Since these arguments were deprecated in a recent version of `tern`, we cannot update the TLG-C without breaking the stable version. This will be fixed by the SME team after the next `tern` release (which should be very soon!)

Required TLG-C changes after release(s) are currently tracked here: https://github.com/insightsengineering/tlg-catalog/issues/157
Feel free to add anything else you notice to this issue :)

Thanks!

**Comment by edelarua** [comment]
Closing as this issue is already documented in #157.
