### ISSUE TITLE
[Bug]: The dev version of the catalog does not use the dev version of packages

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/tlg-catalog#267]
### What happened?

Checking the `sessionInfo` for the shinylive app in the catalog shows that the packages are installed from https://repo.r-wasm.org and not https://pharmaverse.r-universe.dev even after setting the `webr_pkg_repos` option for the repos.
I still do not know why this happens. There are two interesting observations though: 
1. Once a package is installed the shinylive does not reinstall them, this can be tested in a fresh [shinylive editor](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMASwgGdSoAbJjVKAgaygHM46AFAHJyzIQEoAOhHZdecAGpwATnWolhophOm0GzVrO59BIuGNwACZXFRE6AXgIDJYZQFoArhGoA3FXRwrpYOlq4AFqSkqHSIAPRxqOFQyjBQ-qpwGB7efgFZACZwvq5WfKQA8qik6hAuYADucABGygD6qJw8bTZ2dK7ig9JG8kqqtZrm2lIQYAC+ALpAA) or [webr repl](https://webr.r-wasm.org/latest/) instance when these lines are executed it can be observed that the package `teal` is not updated when installed for the next time.
```r
install.packages('teal')
packageVersion('teal')
# [1] ‘0.15.2’
install.packages('teal', repos=c("r-universe" = "https://pharmaverse.r-universe.dev", getOption("webr_pkg_repos")))
packageVersion('teal')
# [1] ‘0.15.2’
```
```r
install.packages('teal', repos=c("r-universe" = "https://pharmaverse.r-universe.dev", getOption("webr_pkg_repos")))
packageVersion('teal')
# [1] ‘0.15.2.9063’
install.packages('teal')
packageVersion('teal')
# [1] ‘0.15.2.9063’
```
2. Perhaps, the webR binary repo (https://repo.r-wasm.org) is given precedence, causing this unexpected behavior, and the package is also installed during a library call if it is not installed. It could be that this call does not account for the `webr_pkg_repos` option and just uses the `https://repo.r-wasm.org`

<img width="1462" alt="Screenshot 2024-09-23 at 7 31 11 AM" src="https://github.com/user-attachments/assets/48e78152-ce2c-4097-9635-0f961228f567">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Thanks! I will have a look at this

**Comment by pawelru** [comment]
This applies only for shinylive - the other `coatless/webr` extension used for static output works as intended.
I believe that this is being determined during rendering the book which tries to build the cache of binaries. Looking at the results - we have `teal@0.15.2` (i.e. the latest release) for both [stable](https://github.com/insightsengineering/tlg-catalog/tree/gh-pages/stable/site_libs/quarto-contrib/shinylive-0.5.0/shinylive/webr/packages/teal) and [devel](https://github.com/insightsengineering/tlg-catalog/tree/gh-pages/development/site_libs/quarto-contrib/shinylive-0.5.0/shinylive/webr/packages/teal).
Now looking into the functionality itself (namely: [this](https://github.com/posit-dev/r-shinylive/blob/bd17fc8191fcda9591538cb6e3542ea5e1b5f488/R/packages.R#L137) function), it looks like it's reading the DESCRIPTION of already installed packages (!) and based on that decides which repo to pull the webr binaries from. In order to use r-universe webr binaries we would have to install R packages from there. Currently this is done by staged.deps which is cloning the repos and install from local. We would have introduce some big changes in the way how we install dependent packages. Luckily, this is in progress and it's tracked [here](https://github.com/insightsengineering/idr-tasks/issues/796). I hope it won't be difficult to configure r-universe into this.
Alternative is to disable creating cache during the render and force installing all during the runtime. This is a [new feature](https://github.com/posit-dev/r-shinylive/blob/bd17fc8191fcda9591538cb6e3542ea5e1b5f488/NEWS.md?plain=1#L7), currently available in the development version only.
I think I am leaning towards the latter because of simplicity. I would have to check the performance though. Therefore I think I will keep this open until that feature becomes available. For the time being - unfortunately we would have to live with this.

**Comment by pawelru** [comment]
There are some significant changes in shinylive that will be about the released (the package itself, shinylive assets and webR package). I will come back to this after this happens.
https://github.com/posit-dev/r-shinylive/issues/134
